CREATE USER blog WITH PASSWORD 'blog';

ALTER USER blog WITH SUPERUSER;

CREATE DATABASE blog WITH OWNER = blog TABLESPACE = pg_default TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'pt_BR.UTF-8' LC_CTYPE = 'pt_BR.UTF-8' CONNECTION LIMIT = -1;

\connect blog

CREATE SCHEMA blog AUTHORIZATION blog;

GRANT ALL ON SCHEMA blog TO blog WITH GRANT OPTION;

CREATE EXTENSION unaccent SCHEMA blog;
